=== VicNew/poc_nisc_service_assurance_system_api/src/main/api/schemas/NetworkServiceMessageSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://newtoms.com/root.json",
  "type": "object",
  "title": "Network Service Message Schema",
  "required": [
    "ServiceId",
    "Name",
    "Description",
    "Status",
    "Type",
    "Zone",
    "TotalRackNumber",
    "FreeRackNumber",
    "PerformanceStatus",
    "QualityServiceStatus",
    "NetworkTest",
    "Traffic",
    "TroubleTicket",
    "Customers",
    "links"
  ],
  "properties": {
    "ServiceId": {
      "$id": "#/properties/ServiceId",
      "type": "integer",
      "title": "The Serviceid Schema",
      "default": 0,
      "examples": [
        1234
      ]
    },
    "Name": {
      "$id": "#/properties/Name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "Service Name"
      ],
      "pattern": "^(.*)$"
    },
    "Description": {
      "$id": "#/properties/Description",
      "type": "string",
      "title": "The Description Schema",
      "default": "",
      "examples": [
        "Service Description"
      ],
      "pattern": "^(.*)$"
    },
    "Status": {
      "$id": "#/properties/Status",
      "type": "string",
      "title": "The Status Schema",
      "default": "",
      "examples": [
        "Active"
      ],
      "pattern": "^(.*)$"
    },
    "Type": {
      "$id": "#/properties/Type",
      "type": "string",
      "title": "The Type Schema",
      "default": "",
      "examples": [
        "Internet"
      ],
      "pattern": "^(.*)$"
    },
    "Zone": {
      "$id": "#/properties/Zone",
      "type": "string",
      "title": "The Zone Schema",
      "default": "",
      "examples": [
        "Center"
      ],
      "pattern": "^(.*)$"
    },
    "TotalRackNumber": {
      "$id": "#/properties/TotalRackNumber",
      "type": "integer",
      "title": "The Totalracknumber Schema",
      "default": 0,
      "examples": [
        100
      ]
    },
    "FreeRackNumber": {
      "$id": "#/properties/FreeRackNumber",
      "type": "integer",
      "title": "The Freeracknumber Schema",
      "default": 0,
      "examples": [
        50
      ]
    },
    "PerformanceStatus": {
      "$id": "#/properties/PerformanceStatus",
      "type": "string",
      "title": "The Performancestatus Schema",
      "default": "",
      "examples": [
        "OK"
      ],
      "pattern": "^(.*)$"
    },
    "QualityServiceStatus": {
      "$id": "#/properties/QualityServiceStatus",
      "type": "string",
      "title": "The Qualityservicestatus Schema",
      "default": "",
      "examples": [
        "OK"
      ],
      "pattern": "^(.*)$"
    },
    "NetworkTest": {
      "$id": "#/properties/NetworkTest",
      "type": "string",
      "title": "The Networktest Schema",
      "default": "",
      "examples": [
        "OK"
      ],
      "pattern": "^(.*)$"
    },
    "Traffic": {
      "$id": "#/properties/Traffic",
      "type": "string",
      "title": "The Traffic Schema",
      "default": "",
      "examples": [
        "OK"
      ],
      "pattern": "^(.*)$"
    },
    "TroubleTicket": {
      "$id": "#/properties/TroubleTicket",
      "type": "array",
      "title": "The Troubleticket Schema",
      "items": {
        "$id": "#/properties/TroubleTicket/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "TicketId",
          "link"
        ],
        "properties": {
          "TicketId": {
            "$id": "#/properties/TroubleTicket/items/properties/TicketId",
            "type": "string",
            "title": "The Ticketid Schema",
            "default": "",
            "examples": [
              "1"
            ],
            "pattern": "^(.*)$"
          },
          "link": {
            "$id": "#/properties/TroubleTicket/items/properties/link",
            "type": "object",
            "title": "The Link Schema",
            "required": [
              "rel",
              "uri",
              "method"
            ],
            "properties": {
              "rel": {
                "$id": "#/properties/TroubleTicket/items/properties/link/properties/rel",
                "type": "string",
                "title": "The Rel Schema",
                "default": "",
                "examples": [
                  "/linkrels/networkService/ticket/info"
                ],
                "pattern": "^(.*)$"
              },
              "uri": {
                "$id": "#/properties/TroubleTicket/items/properties/link/properties/uri",
                "type": "string",
                "title": "The Uri Schema",
                "default": "",
                "examples": [
                  "/network/service/1234/ticket/1"
                ],
                "pattern": "^(.*)$"
              },
              "method": {
                "$id": "#/properties/TroubleTicket/items/properties/link/properties/method",
                "type": "string",
                "title": "The Method Schema",
                "default": "",
                "examples": [
                  "GET"
                ],
                "pattern": "^(.*)$"
              }
            }
          }
        }
      }
    },
    "Customers": {
      "$id": "#/properties/Customers",
      "type": "array",
      "title": "The Customers Schema",
      "items": {
        "$id": "#/properties/Customers/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "CustomerId",
          "link"
        ],
        "properties": {
          "CustomerId": {
            "$id": "#/properties/Customers/items/properties/CustomerId",
            "type": "string",
            "title": "The Customerid Schema",
            "default": "",
            "examples": [
              "1"
            ],
            "pattern": "^(.*)$"
          },
          "link": {
            "$id": "#/properties/Customers/items/properties/link",
            "type": "object",
            "title": "The Link Schema",
            "required": [
              "rel",
              "uri",
              "method"
            ],
            "properties": {
              "rel": {
                "$id": "#/properties/Customers/items/properties/link/properties/rel",
                "type": "string",
                "title": "The Rel Schema",
                "default": "",
                "examples": [
                  "/linkrels/networkService/Customer/info"
                ],
                "pattern": "^(.*)$"
              },
              "uri": {
                "$id": "#/properties/Customers/items/properties/link/properties/uri",
                "type": "string",
                "title": "The Uri Schema",
                "default": "",
                "examples": [
                  "/network/service/1234/customer/1"
                ],
                "pattern": "^(.*)$"
              },
              "method": {
                "$id": "#/properties/Customers/items/properties/link/properties/method",
                "type": "string",
                "title": "The Method Schema",
                "default": "",
                "examples": [
                  "GET"
                ],
                "pattern": "^(.*)$"
              }
            }
          }
        }
      }
    },
    "links": {
      "$id": "#/properties/links",
      "type": "array",
      "title": "The Links Schema",
      "items": {
        "$id": "#/properties/links/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "rel",
          "uri",
          "method"
        ],
        "properties": {
          "rel": {
            "$id": "#/properties/links/items/properties/rel",
            "type": "string",
            "title": "The Rel Schema",
            "default": "",
            "examples": [
              "/linkrels/networkService/info"
            ],
            "pattern": "^(.*)$"
          },
          "uri": {
            "$id": "#/properties/links/items/properties/uri",
            "type": "string",
            "title": "The Uri Schema",
            "default": "",
            "examples": [
              "/network/service/1234"
            ],
            "pattern": "^(.*)$"
          },
          "method": {
            "$id": "#/properties/links/items/properties/method",
            "type": "string",
            "title": "The Method Schema",
            "default": "",
            "examples": [
              "GET"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    }
  }
}

=== VicNew/poc_nisc_service_assurance_system_api/src/main/api/examples/NetworkServiceMessage.json
{
   "ServiceId":1234,
   "Name":"Service Name",
   "Description":"Service Description",
   "Status":"Active",
   "Type":"Internet",
   "Zone":"Center",
   "TotalRackNumber":100,
   "FreeRackNumber":50,
   "PerformanceStatus":"OK",
   "QualityServiceStatus":"OK",
   "NetworkTest":"OK",
   "Traffic":"OK",
   "TroubleTicket":[
      {
         "TicketId":"1",
         "link":{
            "rel":"/linkrels/networkService/ticket/info",
            "uri":"/network/service/1234/ticket/1",
            "method":"GET"
         }
      },
      {
         "TicketId":"2",
         "link":{
            "rel":"/linkrels/networkService/ticket/info",
            "uri":"/network/service/1234/ticket/2",
            "method":"GET"
         }
      }
   ],
   "Customers":[
      {
         "CustomerId":"1",
         "link":{
            "rel":"/linkrels/networkService/Customer/info",
            "uri":"/network/service/1234/customer/1",
            "method":"GET"
         }
      },
      {
         "CustomerId":"2",
         "link":{
            "rel":"/linkrels/networkService/Customer/info",
            "uri":"/network/service/1234/customer/1",
            "method":"GET"
         }
      }
   ],
   "links":[
      {
         "rel":"/linkrels/networkService/info",
         "uri":"/network/service/1234",
         "method":"GET"
      },
      {
         "rel":"/linkrels/networkService/updateInfo",
         "uri":"/network/service/1234",
         "method":"PUT"
      },
      {
         "rel":"/linkrels/networkService/delete",
         "uri":"/network/service/1234",
         "method":"DELETE"
      }
   ]
}
